baseURL = "https://cs-105.github.io/"
languageCode = "en-us"
title = "Minimal"
theme = "minimal"
# disqusShortname = #"username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Noah Spahn"
    description = "Personal blog theme powered by Hugo"
    githubUsername = "#"
    accent = "maroon"
    showBorder = false
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    #profilePic = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.0ua9PBMKBriUSXDm7yISoAHaLH%26pid%3DApi&f=1"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/group_project/"
    name = "Group Project"
    weight = 2

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

#[[menu.icon]]
#    url = "mailto:me@example.com"
#    name = "fas fa-envelope"
#    weight = 1
#
#[[menu.icon]]
#    url = "https://github.com/username/"
#    name = "fab fa-github"
#    weight = 2
#
#[[menu.icon]]
#    url = "https://twitter.com/username/"
#    name = "fab fa-twitter"
#    weight = 3
#
#[[menu.icon]]
#    url = "https://www.linkedin.com/in/username/"
#    name = "fab fa-linkedin"
#    weight = 4
#
#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "fab fa-stack-overflow"
#    weight = 5
